<?php

namespace App\Enums\SimulationCalculator;

use App\Enums\FantasyCalculator\FantasyDraftCategoryType;

final class SimulationCategoryType extends FantasyDraftCategoryType
{
  const PHYSICAL = 'physical';
  const SUMMARY = null;

  // const SUMMARY = null;
  public static function getValues(array|string|null $keys = null): array
  {
    return array_values(array_diff(parent::getValues($keys), [self::SUMMARY])); // TODO: Change the autogenerated stub
  }
}
