<?php

use App\Enums\Opta\Player\PlayerDailyPosition;
use App\Enums\Opta\Player\PlayerPosition;

// plate card 가격 산정을 위한 power raking 산출
$commonPositionTable = [
  PlayerPosition::ATTACKER =>  [
    'goals-att_pen_goal' => 16,
    'att_obox_goal' => 10,
    'att_pen_goal' => 5.5,
    'goal_assist' => 5,
    'penalty_save' => 0,
    'clean_sheet' => 0,
    'game_won' => 3,
    'total_att_assist' => 1.5,
    'ontarget_scoring_att' => 1.5,
    'saves' => 0,
    'interception' => 0.5,
    'won_tackle' => 0.45,
    'outfielder_block' => 0.3,
    'effective_clearance' => 0.5,
    'duel_won' => 0.5,
    'won_contest' => 0.4,
    'diving_save' => 0,
    'accurate_cross' => 0.4,

    'stand_catch' => 0,
    'aerial_won' => 0.1,
    'accurate_keeper_sweeper' => 0,
    'accurate_pass' => 0.02,
    'poss_won_def3rd+poss_won_mid3rd+poss_won_att3rd' => 0.1,
    'touches_opta' => 0.01,
    'poss_lost_all' => -0.03,
    'yellow_card' => -1,
    'big_chance_missed' => -2,
    'goals_conceded' => 0,
    'game_lost' => -3,
    'att_pen_miss+att_pen_post+att_pen_target' => -4.5,
    'penalty_conceded' => -10,
    'second_yellow' => -14,
    'own_goals' => -15,
    'red_card' => -15,
    'error_lead_to_goal' => -15,
  ],
  PlayerPosition::MIDFIELDER =>  [
    'goals-att_pen_goal' => 16,
    'att_obox_goal' => 10,
    'att_pen_goal' => 6.5,
    'goal_assist' => 5,
    'penalty_save' => 0,
    'clean_sheet' => 0,
    'game_won' => 3,
    'total_att_assist' => 1.5,
    'ontarget_scoring_att' => 1.5,
    'saves' => 0,
    'interception' => 0.6,
    'won_tackle' => 0.6,
    'outfielder_block' => 0.3,
    'effective_clearance' => 0.5,
    'duel_won' => 0.6,
    'won_contest' => 0.4,
    'diving_save' => 0,
    'accurate_cross' => 0.4,

    'stand_catch' => 0,
    'aerial_won' => 0.2,
    'accurate_keeper_sweeper' => 0,
    'accurate_pass' => 0.02,
    'poss_won_def3rd+poss_won_mid3rd+poss_won_att3rd' => 0.1,
    'touches_opta' => 0.01,
    'poss_lost_all' => -0.03,
    'yellow_card' => -1,
    'big_chance_missed' => -3,
    'goals_conceded' => 0,
    'game_lost' => -3,
    'att_pen_miss+att_pen_post+att_pen_target' => -5.5,
    'penalty_conceded' => -10,
    'second_yellow' => -14,
    'own_goals' => -15,
    'red_card' => -15,
    'error_lead_to_goal' => -15,
  ],
  PlayerPosition::DEFENDER =>  [
    'goals-att_pen_goal' => 19,
    'att_obox_goal' => 13,
    'att_pen_goal' => 7.5,
    'goal_assist' => 10,
    'penalty_save' => 0,
    'clean_sheet' => 4,
    'game_won' => 3,
    'total_att_assist' => 1.5,
    'ontarget_scoring_att' => 1.5,
    'saves' => 0,
    'interception' => 1.5,
    'won_tackle' => 0.75,
    'outfielder_block' => 1.5,
    'effective_clearance' => 0.5,
    'duel_won' => 0.4,
    'won_contest' => 0.4,
    'diving_save' => 0,
    'accurate_cross' => 0.4,

    'stand_catch' => 0,
    'aerial_won' => 0.5,
    'accurate_keeper_sweeper' => 0,
    'accurate_pass' => 0.02,
    'poss_won_def3rd+poss_won_mid3rd+poss_won_att3rd' => 0.1,
    'touches_opta' => 0.01,
    'poss_lost_all' => -0.03,
    'yellow_card' => -1,
    'big_chance_missed' => -3,
    'goals_conceded' => -2,
    'game_lost' => -3,
    'att_pen_miss+att_pen_post+att_pen_target' => -6.5,
    'penalty_conceded' => -10,
    'second_yellow' => -14,
    'own_goals' => -15,
    'red_card' => -15,
    'error_lead_to_goal' => -15,
  ],
  PlayerPosition::GOALKEEPER =>  [
    'goals-att_pen_goal' => 40,
    'att_obox_goal' => 30,
    'att_pen_goal' => 20,
    'goal_assist' => 15,
    'penalty_save' => 20,
    'clean_sheet' => 12,
    'game_won' => 5,
    'total_att_assist' => 3,
    'ontarget_scoring_att' => 1.5,
    'saves' => 3.7,
    'interception' => 0.5,
    'won_tackle' => 0.45,
    'outfielder_block' => 0,
    'effective_clearance' => 0.5,
    'duel_won' => 0.4,
    'won_contest' => 0.4,
    'diving_save' => 1.5,
    'accurate_cross' => 0,

    'stand_catch' => 1,
    'aerial_won' => 0.1,
    'accurate_keeper_sweeper' => 0.4,
    'accurate_pass' => 0.1,
    'poss_won_def3rd+poss_won_mid3rd+poss_won_att3rd' => 0.1,
    'touches_opta' => 0,
    'poss_lost_all' => -0.03,
    'yellow_card' => -1,
    'big_chance_missed' => 0,
    'goals_conceded' => -6,
    'game_lost' => -1,
    'att_pen_miss+att_pen_post+att_pen_target' => -7.5,
    'penalty_conceded' => -10,
    'second_yellow' => -14,
    'own_goals' => -15,
    'red_card' => -15,
    'error_lead_to_goal' => -20,
  ]
];

return [
  'FANTASYPOWERRANKING_REFERENCE_TABLE_V0' => [
    'Policy' => [],
    'CombTable' => [
      'position' => [
        PlayerDailyPosition::STRIKER => $commonPositionTable[PlayerPosition::ATTACKER],
        PlayerDailyPosition::ATTACKING_MIDFIELDER => $commonPositionTable[PlayerPosition::MIDFIELDER],
        PlayerDailyPosition::MIDFIELDER => $commonPositionTable[PlayerPosition::MIDFIELDER],
        PlayerDailyPosition::DEFENSIVE_MIDFIELDER => $commonPositionTable[PlayerPosition::MIDFIELDER],
        PlayerDailyPosition::WING_BACK => $commonPositionTable[PlayerPosition::DEFENDER],
        PlayerDailyPosition::DEFENDER => $commonPositionTable[PlayerPosition::DEFENDER],
        PlayerPosition::GOALKEEPER => $commonPositionTable[PlayerPosition::GOALKEEPER],
      ],
      'sub_position' => [
        PlayerPosition::ATTACKER => $commonPositionTable[PlayerPosition::ATTACKER],
        PlayerPosition::MIDFIELDER => $commonPositionTable[PlayerPosition::MIDFIELDER],
        PlayerPosition::DEFENDER => $commonPositionTable[PlayerPosition::DEFENDER],
        PlayerPosition::GOALKEEPER => $commonPositionTable[PlayerPosition::GOALKEEPER],
      ]
    ],
    'Categories' => []
  ]
];
