<?php

namespace Database\Seeders;

use App\Enums\FantasyMeta\RefPlayerTierType;
use App\Models\meta\RefLeagueTier;
use Illuminate\Database\Seeder;

class LeagueTierSeeder extends Seeder
{
  public function run()
  {
    if (RefLeagueTier::all()->isNotEmpty()) {
      return;
    }

    $seedData = [
      [
        'contient' => 'UEFA',
        'country' => 'England',
        'country_id' => '1fk5l4hkqk12i7zske6mcqju6',
        'league_name' => 'Premier League',
        'league_id' => '2kwbbcootiqqgmrzs6o5inle5',
        'tier' => RefPlayerTierType::S,
        'tier_quality' => '6.00',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Spain',
        'country_id' => '49ih1pwv3ahshdf8uzrimi54c',
        'league_name' => 'Primera División',
        'league_id' => '34pl8szyvrbwcmfkuocjm3r6t',
        'tier' => RefPlayerTierType::S,
        'tier_quality' => '5.00',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Italy',
        'country_id' => '25f2cmb2r8mk5rj92tzer6kvv',
        'league_name' => 'Serie A',
        'league_id' => '1r097lpxe0xn03ihb7wi98kao',
        'tier' => RefPlayerTierType::S,
        'tier_quality' => '4.00',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Germany',
        'country_id' => '36min0qztu8eydwvpv8t1is0m',
        'league_name' => 'Bundesliga',
        'league_id' => '6by3h89i2eykc341oz7lv1ddd',
        'tier' => RefPlayerTierType::S,
        'tier_quality' => '3.00',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'France',
        'country_id' => '7gww28djs405rfga69smki84o',
        'league_name' => 'Ligue 1',
        'league_id' => 'dm5ka0os1e3dxcp3vh05kmp33',
        'tier' => RefPlayerTierType::S,
        'tier_quality' => '3.00',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Netherlands',
        'country_id' => '6hzi5pltnz67q4la8yli9qfv6',
        'league_name' => 'Eredivisie',
        'league_id' => 'akmkihra9ruad09ljapsm84b3',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '5.22',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Portugal',
        'country_id' => '1nbm5i9a0403zzvltn17lxinc',
        'league_name' => 'Primeira',
        'league_id' => '8yi6ejjd1zudcqtbn07haahg6',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '5.00',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Brazil',
        'country_id' => '2vufyvpoxd9lfl9f6vpp7tz6y',
        'league_name' => 'Serie A',
        'league_id' => 'scf9p4y91yjvqvg5jndxzhxj',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '2.25',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Argentina',
        'country_id' => '2vovxa97k7v7ofa85dah2xktb',
        'league_name' => 'Liga Profesional Argentina',
        'league_id' => '581t4mywybx21wcpmpykhyzr3',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '2.00',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Belgium',
        'country_id' => '4wbzjcclyefma1ourvjsu4q2j',
        'league_name' => 'First Division A',
        'league_id' => '4zwgbb66rif2spcoeeol2motx',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '1.80',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Scotland',
        'country_id' => '1xf68d0a8lnnq30hnnn8kr6ut',
        'league_name' => 'Premiership',
        'league_id' => 'e21cf135btr8t3upw0vl6n6x0',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '1.60',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Austria',
        'country_id' => 'hcs1bd49qliqqity6o268jyt',
        'league_name' => 'Bundesliga',
        'league_id' => '5c96g1zm7vo5ons9c42uy2w3r',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '1.20',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Serbia',
        'country_id' => '5w4ve503bjdsshwx9ho6jxzx0',
        'league_name' => 'Super Liga',
        'league_id' => '3ww12jab49q8q8mk9avdwjqgk',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '0.90',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Turkey',
        'country_id' => '6kd6webenogylfgwt2aa9l6vx',
        'league_name' => 'Süper Lig',
        'league_id' => '482ofyysbdbeoxauk19yg7tdt',
        'tier' => RefPlayerTierType::A,
        'tier_quality' => '1.50',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Switzerland',
        'country_id' => '3bh70jgvc5mn58x0byjkuda17',
        'league_name' => 'Super League',
        'league_id' => 'e0lck99w8meo9qoalfrxgo33o',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.58',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Czech Republic',
        'country_id' => '5md5tpwr2nmqao528prx43jr7',
        'league_name' => 'Czech Liga',
        'league_id' => 'bu1l7ckihyr0errxw61p0m05',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.56',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Norway',
        'country_id' => '7f16iy4w8u8ogyn6pfooqwv5z',
        'league_name' => 'Eliteserien',
        'league_id' => '9ynnnx1qmkizq1o3qr3v0nsuk',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.50',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Ukraine',
        'country_id' => '315w6fk6umfzf4qvba3t55u61',
        'league_name' => 'Premier League',
        'league_id' => '6wubmo7di3kdpflluf6s8c7vs',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.45',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Denmark',
        'country_id' => '5adf60vwiw2f2mibyq1k4ex7i',
        'league_name' => 'Superliga',
        'league_id' => '29actv1ohj8r10kd9hu0jnb0n',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.27',
      ],
      [
        'contient' => 'CONCACAF',
        'country' => 'Mexico',
        'country_id' => '5trdr3jf42i20zj1hnkvcytr6',
        'league_name' => 'Liga MX',
        'league_id' => '2hsidwomhjsaaytdy9u5niyi4',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.23',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Morocco',
        'country_id' => '2xdcc39z1k79pnjbtn9x31wdh',
        'league_name' => 'Botola Pro',
        'league_id' => '1eruend45vd20g9hbrpiggs5u',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.17',
      ],
      [
        'contient' => 'CONCACAF',
        'country' => 'USA',
        'country_id' => '7hr2f89v44y65dyu9k92vprwn',
        'league_name' => 'MLS',
        'league_id' => '287tckirbfj9nb8ar2k9r60vn',
        'tier' => RefPlayerTierType::B_1,
        'tier_quality' => '0.15',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Croatia',
        'country_id' => '37hlakrwxyuzovaeoo4sezusp',
        'league_name' => 'HNL',
        'league_id' => '1b70m6qtxrp75b4vtk8hxh8c3',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.19',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Greece',
        'country_id' => '6lpgd60z890no2v46zdecrcss',
        'league_name' => 'Super League 1',
        'league_id' => 'c0r21rtokgnbtc0o2rldjmkxu',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.22',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Israel',
        'country_id' => '4bnqn6mt5vyslpxfuqdrcmpgp',
        'league_name' => 'Ligat Haal',
        'league_id' => '2xg0qvif1rh7du6wmk2eleku3',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.27',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Egypt',
        'country_id' => '42vt7mha0thcwd0ihw3p29x5i',
        'league_name' => 'Premier League',
        'league_id' => '8k1xcsyvxapl4jlsluh3eomre',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.34',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Cyprus',
        'country_id' => '3om8cj5nhmq1rzzkykubm5icj',
        'league_name' => '1. Division',
        'league_id' => 'btouq8t23agr62ij7e0ju5p6n',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.50',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Sweden',
        'country_id' => '1z6l2c33w2kyz9rdefs1d68nb',
        'league_name' => 'Allsvenskan',
        'league_id' => 'b60nisd3qn427jm0hrg9kvmab',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.52',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Italy',
        'country_id' => '25f2cmb2r8mk5rj92tzer6kvv',
        'league_name' => 'Serie B',
        'league_id' => '8ey0ww2zsosdmwr8ehsorh6t7',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.90',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'France',
        'country_id' => '7gww28djs405rfga69smki84o',
        'league_name' => 'Ligue 2',
        'league_id' => '4w7x0s5gfs5abasphlha5de8k',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.90',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Spain',
        'country_id' => '49ih1pwv3ahshdf8uzrimi54c',
        'league_name' => 'Segunda División',
        'league_id' => '3is4bkgf3loxv9qfg3hm8zfqb',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.90',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'England',
        'country_id' => '1fk5l4hkqk12i7zske6mcqju6',
        'league_name' => 'Championship',
        'league_id' => '7ntvbsyq31jnzoqoa8850b9b8',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.90',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Brazil',
        'country_id' => '2vufyvpoxd9lfl9f6vpp7tz6y',
        'league_name' => 'Serie B',
        'league_id' => '5zr0b05eyx25km7z1k03ca9jx',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.90',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Russiz',
        'country_id' => '7kfg68kh6n16fs4ap3xjiudr',
        'league_name' => 'Premier League',
        'league_id' => '3ab1uwtoyjopdj1y1fynyy9jg',
        'tier' => RefPlayerTierType::B_2,
        'tier_quality' => '-0.90',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Paraguay',
        'country_id' => '4snnlul02xmgkkb024q2bqyn9',
        'league_name' => 'Division Profesional',
        'league_id' => '5y0z0l2epprzbscvzsgldw8vu',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.96',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Hungary',
        'country_id' => '1vy5vlux7mj2r7r9ktd71hhpo',
        'league_name' => 'NB I',
        'league_id' => '47s2kt0e8m444ftqvsrqa3bvq',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.83',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Ecuador',
        'country_id' => '6pyj2bytt2osbjk69owzfehcg',
        'league_name' => 'Liga Pro',
        'league_id' => '6lwpjhktjhl9g7x2w7njmzva6',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.76',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Romania',
        'country_id' => '17oj2qrzqlkhdjvazum10sx2i',
        'league_name' => 'Liga I',
        'league_id' => '89ovpy1rarewwzqvi30bfdr8b',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.75',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Colombia',
        'country_id' => '6kby8rq1p01fg5ds38ckkrcs5',
        'league_name' => 'Primera A',
        'league_id' => '2ty8ihceabty8yddmu31iuuej',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.70',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Bulgaria',
        'country_id' => '5a1vsxg8tbnsk65iefq1q8tlt',
        'league_name' => 'First League',
        'league_id' => 'c0yqkbilbbg70ij2473xymmqv',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.60',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Slovakia',
        'country_id' => '7dybe8679n9bgyrcxi383pq3y',
        'league_name' => 'Super Liga',
        'league_id' => '1mpjd0vbxbtu9zw89yj09xk3z',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.55',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Netherlands',
        'country_id' => '6hzi5pltnz67q4la8yli9qfv6',
        'league_name' => 'Eerste Divisie',
        'league_id' => '1gwajyt0pk2jm5fx5mu36v114',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.40',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Portugal',
        'country_id' => '1nbm5i9a0403zzvltn17lxinc',
        'league_name' => 'Segunda Liga',
        'league_id' => '8sdpk4aerruf515yh76ezo7vi',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.40',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Poland',
        'country_id' => '27baqb7359ywdvsxxklx1kn11',
        'league_name' => 'Ekstraklasa',
        'league_id' => '7hl0svs2hg225i2zud0g3xzp2',
        'tier' => RefPlayerTierType::C_1,
        'tier_quality' => '0.40',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Belgium',
        'country_id' => '4wbzjcclyefma1ourvjsu4q2j',
        'league_name' => 'Challenger Pro League',
        'league_id' => 'af79lqrc0ntom74zq13ccjslo',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.09',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Austria',
        'country_id' => 'hcs1bd49qliqqity6o268jyt',
        'league_name' => '2. Liga',
        'league_id' => 'a7247po5qs29o3zsfmt222ydu',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.09',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Azerbaijan',
        'country_id' => '52sufqqq7vid3xa6iljx6obcz',
        'league_name' => 'Premyer Liqa',
        'league_id' => '3428tckxcirwwh3o3jgc1m8ji',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.09',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Algeria',
        'country_id' => '1ayprcriqhb8iv10ch70clppu',
        'league_name' => 'Ligue 1',
        'league_id' => '57nu0wygurzkp6fuy5hhrtaa2',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.09',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Uruguay',
        'country_id' => '286fwlvd6dzntv6ewv3cyvb0p',
        'league_name' => 'Primera División',
        'league_id' => '2wolc27r8z03itcvwp43e38c5',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.12',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Tunisia',
        'country_id' => '2um1icx6ftp1auliaxyw0ou6y',
        'league_name' => 'Ligue 1',
        'league_id' => 'f4jc2cc5nq7flaoptpi5ua4k4',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.15',
      ],
      [
        'contient' => 'CAF',
        'country' => 'South Africa',
        'country_id' => '1kiwby3xmt97m3ejw76qs4i6k',
        'league_name' => 'PSL',
        'league_id' => 'yv73ms6v1995b5wny16jcfi3',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.25',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Saudi Arabia',
        'country_id' => '639nv0r2ixeusx4nzqyzb5iuq',
        'league_name' => 'Saudi League',
        'league_id' => 'ea0h6cf3bhl698hkxhpulh2zz',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.51',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Korea Republic',
        'country_id' => '4vzpxtqkiwx0puygnmayr74di',
        'league_name' => 'K League 1',
        'league_id' => 'avs3xposm3t9x1x2vzsoxzcbu',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.64',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Chile',
        'country_id' => '32tb8d7824xg4i0ybxzssczu0',
        'league_name' => 'Primera División',
        'league_id' => '2y8bntiif3a9y6gtmauv30gt',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.66',
      ],
      [
        'contient' => 'AFC',
        'country' => 'japan',
        'country_id' => 'lxyibh89lpdc0bfian1nx0xq',
        'league_name' => 'J1 League',
        'league_id' => '8o5tv5viv4hy1qg9jp94k7ayb',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.70',
      ],
      [
        'contient' => 'CONCACAF',
        'country' => 'Costa Rica',
        'country_id' => '48emauy3fucokp86skcs5alh8',
        'league_name' => 'Primera División',
        'league_id' => 'civf31q1inxohs4a03y8reetf',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.76',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Kazakhstan',
        'country_id' => '6kewn14jj4ncyzghlbu61hna6',
        'league_name' => 'Premier League',
        'league_id' => '9ikchyu9fb8bvx0s673jofj6s',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.80',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Slovenia',
        'country_id' => '63vptz9g2ckqnnlxhd1oqn4xq',
        'league_name' => '1. SNL',
        'league_id' => '7nmz249q89qg5ezcvzlheljji',
        'tier' => RefPlayerTierType::C_2,
        'tier_quality' => '-0.83',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Moldova',
        'country_id' => '389mdnq78a55g2gr040a3mmtj',
        'league_name' => 'Super Liga',
        'league_id' => '1j4ehtrbry9depwt6oghaq3lu',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.47',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Kosovo',
        'country_id' => '86u6edbqifdjsn49mbp2anw7p',
        'league_name' => 'Superliga',
        'league_id' => 'dwiqifdd70ytjytcs09vzosb3',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.32',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Iran',
        'country_id' => 'e53g9hr2d3kasm34uumbg8r4',
        'league_name' => 'Persian Gulf Pro League',
        'league_id' => '3btdfgw79qiz3jmyfudovtbu2',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.30',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Latvia',
        'country_id' => '6s9bglosczqlp9cxh3ze5hdm5',
        'league_name' => 'Virsliga',
        'league_id' => '3w1hkk9k9gr8fwssyn4icvdfo',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.24',
      ],
      [
        'contient' => 'AC',
        'country' => 'Qatar',
        'country_id' => '1evdpix889bnpu5wgh6ae7kng',
        'league_name' => 'Stars League',
        'league_id' => 'xaouuwuk8qyhv1libkeexwjh',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.22',
      ],
      [
        'contient' => 'CONCACAF',
        'country' => 'Canada',
        'country_id' => '1iaoypzp6syf32cz9l15pzp7e',
        'league_name' => 'Canadian Premier League',
        'league_id' => '6lkj3o21cr4g7bql6tb3fk222',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.21',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Republic of Ireland',
        'country_id' => '63nepb66un7juhglo2g6rezcl',
        'league_name' => 'Premier Division',
        'league_id' => '4mbfidy8zum5u0aqjqo0vuqs2',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.19',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Finland',
        'country_id' => '2u07e54v5dprsugdvddpq5ync',
        'league_name' => 'Veikkausliiga',
        'league_id' => 'dvstmwnvw0mt5p38twn9yttyb',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.16',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Lithuania',
        'country_id' => '366yd1wf1hzvvjb5u6r59rl1w',
        'league_name' => 'A Lyga',
        'league_id' => '5cwsxtx37les6m10xj71htkgf',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.11',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Belarus',
        'country_id' => '2vn7xzv9g752y1h5ufjzr27i8',
        'league_name' => 'Premier League',
        'league_id' => '8y29fg2s85ppcb8uugm5ee8s4',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.09',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Armenia',
        'country_id' => '687vx665s4d88stgnq72a84k6',
        'league_name' => 'Premier League',
        'league_id' => 'dn9kmfdbz74lzt3m8e9g0vwjq',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.09',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Bolivia',
        'country_id' => '3dgy24s32p56l29s66imputcy',
        'league_name' => 'Premijer Liga',
        'league_id' => 'alpfd99yd3lfv7bhjo0biuq7b',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.08',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Bosnia and Herzegovina',
        'country_id' => '4fue8u54361o79fbiu9qwxjer',
        'league_name' => 'Premijer Liga',
        'league_id' => '4yngyfinzd6bb1k7anqtqs0wt',
        'tier' => RefPlayerTierType::D_1,
        'tier_quality' => '0.06',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Venezuela',
        'country_id' => '1er0616j12s9yghuzvsx76d5v',
        'league_name' => 'Primera División',
        'league_id' => '46b141eaqq9q7o4gz5gtdpikk',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.07',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Luxembourg',
        'country_id' => 'f2r46apchse9eg3n9c9pupfs',
        'league_name' => 'National Division',
        'league_id' => '48pg4xminsjxun5x4yp5ng8v',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.09',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Congo DR',
        'country_id' => '6xq2smnxqvc5bh7vzza9ljiy9',
        'league_name' => 'Ligue 1',
        'league_id' => '7pl8j3qzfufcquaf8kvduau2r',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.13',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Faroe Islands',
        'country_id' => '1glg6jsz6v1fkk8y9pq4fqjc4',
        'league_name' => 'Meistaradeildin',
        'league_id' => 'dr2xk7muj8aqcjdz2b3li1c0k',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.14',
      ],
      [
        'contient' => 'CONMEBOL',
        'country' => 'Peru',
        'country_id' => '2uib9hdovpcye4re2l3omr4dl',
        'league_name' => 'Primera División',
        'league_id' => 'a9vrdkelbgif0gtu3wxsr75xo',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.17',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Northern Ireland',
        'country_id' => '5euslv7jutsauoqt3o2lj9bvi',
        'league_name' => 'Premiership',
        'league_id' => '75i269i1ak43magshljadydrh',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.18',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Malta',
        'country_id' => '52j1myzb4go3nqu8crtu7ulc1',
        'league_name' => 'Premier League',
        'league_id' => '5taraea6mqjjldg9zxswo825y',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.25',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Georgia',
        'country_id' => '55mqz7j6585f2jhgfhn62lomr',
        'league_name' => 'Erovnuli Liga',
        'league_id' => '477yyajzheg2z8u7uick0e13e',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.30',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Estonia',
        'country_id' => '64smib5liu1qh78iaylufxj99',
        'league_name' => 'Meistriliiga',
        'league_id' => '4d5d3sf6805n5u6jdoa0hdlog',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.38',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Uzbekistan',
        'country_id' => '8j3qx8u2xs9yc8u8b3n1r31k',
        'league_name' => 'Super League',
        'league_id' => '1snn4i06dn6n11mrfc894snzm',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.45',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Iceland',
        'country_id' => '4jjsm5a20nnxgw5cus6b7yxc6',
        'league_name' => 'Úrvalsdeild',
        'league_id' => 'zilopfej2h0n3vpan5tcynpo',
        'tier' => RefPlayerTierType::D_2,
        'tier_quality' => '-0.45',
      ],
      [
        'contient' => 'AFC',
        'country' => 'China',
        'country_id' => '6e8huv1g6g173rptk3y6jsg5z',
        'league_name' => 'CSL',
        'league_id' => '82jkgccg7phfjpd0mltdl3pat',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.57',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Angola',
        'country_id' => '3k53bkrjx5zsxchc6e3mcd834',
        'league_name' => 'Girabola',
        'league_id' => '6c76ua2pykvzepkmpprq4i8kf',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.51',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Albania',
        'country_id' => '17zsm8shejejls2on1ffil3op',
        'league_name' => 'Superliga',
        'league_id' => '1zcp6rnjil25rnsv1ttcz3dhx',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.48',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Wales',
        'country_id' => '26ilvvgth36hmq6lgq8cy5cb5',
        'league_name' => 'Premier League',
        'league_id' => 'c76z5d6j7dpi1e79tm8fpm39z',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.46',
      ],
      [
        'contient' => 'AFC',
        'country' => 'United Arab Emirates',
        'country_id' => '13y072b531iotfuk9ll20xt4u',
        'league_name' => 'Pro League',
        'league_id' => 'f39uq10c8xhg5e6rwwcf6lhgc',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.41',
      ], [
        'contient' => 'AFC',
        'country' => 'Thailand',
        'country_id' => '71wqq15l0mvpl4lneayzzh44g',
        'league_name' => 'Thai League 1',
        'league_id' => 'iu1vi94p4p28oozl1h9bvplr',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.39',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Gibraltar',
        'country_id' => '1uebysp0nph4vtqw6gsv347jw',
        'league_name' => 'Premier Division',
        'league_id' => 'dzu6b07r25e3pk2uahxi5mzsz',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.38',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'North Macedonia',
        'country_id' => '1lesyxylc5eza0a4z87t9azcc',
        'league_name' => 'First League',
        'league_id' => 'dl5v19e4466jn4fuufhlae7jm',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.32',
      ],
      [
        'contient' => 'CONCACAF',
        'country' => 'Panama',
        'country_id' => '5nhk7v9jq6dqmfbn4hiihhofv',
        'league_name' => 'LPF',
        'league_id' => '2ni5x4ta0fv1zxee9l10rp1bz',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.30',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Jordan',
        'country_id' => '5067agkwm6luzilwyfwth1dic',
        'league_name' => 'League',
        'league_id' => '145hkd59i6foieuwr4mwi6wlq',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.26',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Andorra',
        'country_id' => '6kxfttvbfkg4ywupx6g9zc16o',
        'league_name' => '1a Divisió',
        'league_id' => 'ejunkmfhjz9weugd2bqrkgobb',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.25',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'Montenegro',
        'country_id' => '1411jebgwo2ja1erogsq81lg9',
        'league_name' => 'First League',
        'league_id' => '77yifp2y2tvn80ndo3f0laav8',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.17',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Sudan',
        'country_id' => '62wa0a1wwukxladeo5kqhrpen',
        'league_name' => 'Sudani Premier League',
        'league_id' => '2c01jrik7ggtta321pstz8tm4',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.16',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Libya',
        'country_id' => 'u42u510tspw3jy1ihkb3mdx9',
        'league_name' => 'Premier League',
        'league_id' => '83ib9ygyuj24tov28t0ihv2le',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.14',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Hong Kong',
        'country_id' => '5mqvtybzlyttafefvps14mvt3',
        'league_name' => 'Premier League',
        'league_id' => '4rls982p5uzil6x30mhyhv9f3',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.14',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Guinea',
        'country_id' => '4i9sg55wigitrfx7290f59ceo',
        'league_name' => 'Ligue 1',
        'league_id' => '34txpgicm59r0bd60berrxhed',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.09',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Tanzania',
        'country_id' => '3rramsla3ovuhxks28wq1kirb',
        'league_name' => 'Ligi kuu Bara',
        'league_id' => '9z5643nd06afqu01ea2wt8y4g',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.07',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Tajikistan',
        'country_id' => '89gz6ggxg3ln21e4xjdfbc3n',
        'league_name' => 'Vysshaya Liga',
        'league_id' => '4gv4fxg1q7qxdubycjhbiqsl7',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.06',
      ],
      [
        'contient' => 'CONCACAF',
        'country' => 'Jamaica',
        'country_id' => 'gimxu1vjwoa2xrecyd9gtyoc',
        'league_name' => 'Premier League',
        'league_id' => '6lrwyoy74oz0t5udrnmuyql6a',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.03',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Iraq',
        'country_id' => '1uzblzx1s42jn6zk6hivjzby8',
        'league_name' => 'Iraqi League',
        'league_id' => 'duuc1qczfnawwncru1ly6o66',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.01',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Korea Republic',
        'country_id' => '4vzpxtqkiwx0puygnmayr74di',
        'league_name' => 'K League 2',
        'league_id' => 'b73zounsynk9d3u1p9nvpu7i2',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.00',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Vietnam',
        'country_id' => '747si8rr6manolqh31d1vz17q',
        'league_name' => 'V.League 1',
        'league_id' => 'aho73e5udydy96iun3tkzdzsi',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '0.00',
      ],
      [
        'contient' => 'CAF',
        'country' => 'Nigeria',
        'country_id' => '63pvdwrsiq5b07mzi8igqei9p',
        'league_name' => 'NPFL',
        'league_id' => 'ac42gi3penartj88fe9l6plpk',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.06',
      ], [
        'contient' => 'AFC',
        'country' => 'Turkmenistan',
        'country_id' => '6xf1qvrbv5hkwwjscxlyfavrw',
        'league_name' => 'Ýokary Liga',
        'league_id' => '85d7d2jwmo1xx2pen4hkoclyn',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.16',
      ],
      [
        'contient' => 'AFC',
        'country' => 'India',
        'country_id' => 'pu2isxryiewd7pvejah6oqex',
        'league_name' => 'Indian Super League',
        'league_id' => '3oa9e03e7w9nr8kqwqc3tlqz9',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.22',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Lebanon',
        'country_id' => 'x78kryrxd9j9dfj4mtec292b',
        'league_name' => 'Premier League',
        'league_id' => '3e40pestup9xzagsu2o6c0i8u',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.26',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Philippines',
        'country_id' => '2bn52u7dpgfatwqumx224cczx',
        'league_name' => 'PFL',
        'league_id' => '8ifnkq96dckjtn9ab9wplpl9l',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.27',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Malaysia',
        'country_id' => '2nkhuc4d9vq5llknmxpa0wbhy',
        'league_name' => 'Super League',
        'league_id' => 'eg6s9f1jj7jr6stmbosn0g6c8',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.32',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Bangladesh',
        'country_id' => '7fehvaq75zecgbbo70z41b24o',
        'league_name' => 'Premier League',
        'league_id' => '3c8633feplm71zs185iyado3t',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.35',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Kuwait',
        'country_id' => '70rn9hy1i32yu04uos65wvgs5',
        'league_name' => 'Premier League',
        'league_id' => '3j81qr7yc4gdnakfwnxf95ovh',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.38',
      ],
      [
        'contient' => 'UEFA',
        'country' => 'San Marino',
        'country_id' => '423ba8zqzgmze8xgruw9ggqck',
        'league_name' => 'Campionato',
        'league_id' => '2c63lkabcjzoiqavj24madt2d',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.39',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Australia',
        'country_id' => 'u5ieemi69z72c3bgczyy68lo',
        'league_name' => 'A-League Men',
        'league_id' => 'xwnjb1az11zffwty3m6vn8y6',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.40',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Singapore',
        'country_id' => 'i5ym1phxb6fliphj1xd6pydv',
        'league_name' => 'Premier League',
        'league_id' => '1q4ab2bpg5e8jl1g2udnakrju',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.41',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Bahrain',
        'country_id' => '4j3eg4ch3tdp2uh7kblm8yvvj',
        'league_name' => 'Premier League',
        'league_id' => '82wo38rqeizxlfjjhfjy4rx7u',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.41',
      ],
      [
        'contient' => 'AFC',
        'country' => 'INDONESIA',
        'country_id' => '1zi2c00k6skx48tn692uem0n6',
        'league_name' => 'Liga 1',
        'league_id' => '117yqo02rs8dykkxpm274w3bd',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.43',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Syria ',
        'country_id' => '3tsnzfkszhsktmhsmwar1tvp8',
        'league_name' => 'Premier League',
        'league_id' => '6g4vcneo8yvvf0f9cy38o3hy2',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.52',
      ],
      [
        'contient' => 'AFC',
        'country' => 'Myanmar ',
        'country_id' => 'qr4bp3xzkf0frhwnit3diakz',
        'league_name' => 'Premier League',
        'league_id' => 't2th5fajt23vbdfzhnd6gbbe',
        'tier' => RefPlayerTierType::E,
        'tier_quality' => '-0.57',
      ]
    ];

    foreach ($seedData as $idx => $row) {
      RefLeagueTier::updateOrCreateEx([
        'contient' => $row['contient'],
        'country' => $row['country'],
        'country_id' => $row['country_id'],
        'league_name' => $row['league_name'],
        'league_id' => $row['league_id'],
        'tier' => $row['tier'],
        'tier_quality' => $row['tier_quality'],
      ], $row);
    }
  }
}
